# Generated by Django 5.0.3 on 2024-03-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrecord',
            name='city',
            field=models.CharField(default='city', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientrecord',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientrecord',
            name='province',
            field=models.CharField(max_length=100),
        ),
    ]
