# Generated by Django 5.0.3 on 2024-03-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clientrecord_city_alter_clientrecord_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrecord',
            old_name='email_add',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='clientrecord',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
